import { useRouter } from 'next/router';
import Head from 'next/head';
import { Navbar, Main } from '../components';
import { useAuth } from '../hooks/useAuth';
import { useEffect } from 'react';
import { useDarkMode } from '../hooks/useDarkMode';

export default function Home() {
  const { user } = useAuth();
  const router = useRouter();

  const { darkMode } = useDarkMode();

  useEffect(() => {
    if (!user) {
      router.push('/login');
    }
  }, [user]);
  
  return (
    <div className={`${darkMode && 'dark'}`}>
      <Head>
        <title>Techie Trainer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='min-h-screen bg-neutral-200 dark:bg-neutral-500 text-gray-800 dark:text-gray-300'>
        <Navbar />

        <Main />

        {/* Footer */}
      </div>
    </div>
  )
}
